# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

#### 3. Create a null vector of size 10 (★☆☆)

#### 4. How to find the memory size of any array (★☆☆)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

#### 11. Create a 3x3 identity matrix (★☆☆)

#### 12. Create a 3x3x3 array with random values (★☆☆)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [14]:
z = np.zeros((5,5), dtype = np.int32)

for i in range(5):
    for j in range(5):
        if j - i == -1:
            z[i,j] = i 
            
print(z) 

print()

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [48]:
Z1 = np.zeros((8,8), dtype = np.uint8)

box = 0 
for i in range(8):
    for j in range(8):
        if (i+j)%2 !=0 :
            Z1[i,j] = 1

print(Z1)
print()

Z2 = np.zeros((8,8),dtype=int)

Z2[1::2,::2] = 1
Z2[::2,1::2] = 1

print(Z2)

Z1 == Z2



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [59]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [79]:
dir(np.tile)
!python -c "import numpy; numpy.info(numpy.tile)"

 tile(A, reps)

Construct an array by repeating A the number of times given by reps.

If `reps` has length ``d``, the result will have dimension of
``max(d, A.ndim)``.

If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
or shape (1, 1, 3) for 3-D replication. If this is not the desired
behavior, promote `A` to d-dimensions manually before calling this
function.

If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
(1, 1, 2, 2).

Note : Although tile may be used for broadcasting, it is strongly
recommended to use numpy's broadcasting operations and functions.

Parameters
----------
A : array_like
    The input array.
reps : array_like
    The number of repetitions of `A` along each axis.

Returns
-------
c : ndarray
    The tiled output array.

See Also
--------
repeat : Repeat elements of an array.
br

In [91]:
z = np.array([[0,1],[1,0]])
Z = np.tile(z,(4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [94]:
Z = np.random.random((5,5))Z
Z = (Z - Z.mean())/Z.std()

Z = (Z - np.mean (Z)) / (np.std (Z))


array([[-1.11654587, -0.42041795, -1.21719591,  0.70552833,  1.14550264],
       [-1.0019589 , -1.19959059,  1.04930398, -1.12935129, -0.84449606],
       [ 2.16986729,  0.38243691,  0.3465481 , -0.3324544 ,  0.92977739],
       [ 0.86937424, -0.76113556,  1.41244445,  0.60384689, -0.80733969],
       [-1.57714158, -0.21561953,  1.32186739,  0.09432887, -0.40757914]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [100]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [106]:
x = np.random.random((5,3))
y = x.T

z1 = np.matmul(x,y)
z2 = np.dot(x,y)
z3 = x @ y 

# z1==z2
# z1==z3

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [147]:
Z = np.random.random((10))*10
print(Z)

np.array([-x if  x < 8.0 and x > 3 else x for x in list(Z)])

# [f(x) if condition else g(x) for x in sequence]

[6.57143593 4.33320044 7.15981822 3.24060345 7.16365041 2.00537695
 9.86978835 9.0726204  2.32602254 1.90430776]


array([-6.57143593, -4.33320044, -7.15981822, -3.24060345, -7.16365041,
        2.00537695,  9.86978835,  9.0726204 ,  2.32602254,  1.90430776])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [151]:
sum(range(5))

10

In [1]:
print(sum(range(5),-1))    # 9 
from numpy import *
print(sum(range(5),-1))     # 10 

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [9]:
import numpy as np
Z = np.array([1,2,3,5,6,9])

Z**Z     # allowed
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z   # throws error

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [18]:
Z = np.random.uniform(low=-1, high=1, size=(10,))
Z = np.random.normal(loc=-1, scale=1, size=(10,))

print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-1. -1. -1. -2. -2. -4. -2. -1. -1. -1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
Z1 = np.random.randint(low=0, high=10, size=(10,))
Z2 = np.random.randint(low=0, high=10, size=(10,))

print(Z1[Z1==Z2])               # matches only at same index
print(np.intersect1d(Z1,Z2))    # finds intesection 


[]
[0 1 2 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
defaults = np.seterr(all="ignore")

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [38]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64("today")
tomorrow = np.datetime64("today") + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [40]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

type(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


numpy.ndarray

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [41]:
A = np.ones(3)*1
B = np.ones(3)*2

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [66]:
Z = np.random.uniform(low=0, high=10, size=(10,))

ans1 = np.array([np.ceil(x) if x < 0  else np.floor(x) for x in Z], dtype = float)

ans2 = np.floor(Z)


ans1 ==ans2, ans1,ans2

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]),
 array([9., 7., 1., 0., 8., 2., 2., 1., 7., 3.]),
 array([9., 7., 1., 0., 8., 2., 2., 1., 7., 3.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [110]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [91]:
np.random.randint((10))

9

In [109]:
def gen():
    for x in range(10):
        yield x
        
for g in gen():
    print(g)
    break

0


In [104]:
def generate():
    for x in range(10):
        yield x
        
Z = np.fromiter(generate(),dtype=float,count=-1)

print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)
Z.sort()
print(Z)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [119]:
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]

R = np.sqrt(X**2 + Y**2)
theta = np.arctan2(Y,X)
R,theta

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

(array([0.94790913, 0.48664881, 0.41521448, 0.84454703, 0.37320515,
        1.11759874, 0.60606929, 0.86496968, 0.93094235, 0.27645017]),
 array([1.19998662, 0.60029625, 0.98611691, 0.2110068 , 0.93315426,
        0.98303796, 1.32135209, 0.91629727, 1.18906133, 0.99898166]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [127]:
Z = np.random.random(10)
Z[Z.argmax()] = 0

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [137]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

G



array([[0.36787944, 0.44822088, 0.51979489, 0.57375342, 0.60279818,
        0.60279818, 0.57375342, 0.51979489, 0.44822088, 0.36787944],
       [0.44822088, 0.54610814, 0.63331324, 0.69905581, 0.73444367,
        0.73444367, 0.69905581, 0.63331324, 0.54610814, 0.44822088],
       [0.51979489, 0.63331324, 0.73444367, 0.81068432, 0.85172308,
        0.85172308, 0.81068432, 0.73444367, 0.63331324, 0.51979489],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.60279818, 0.73444367, 0.85172308, 0.9401382 , 0.98773022,
        0.98773022, 0.9401382 , 0.85172308, 0.73444367, 0.60279818],
       [0.57375342, 0.69905581, 0.81068432, 0.89483932, 0.9401382 ,
        0.9401382 , 0.89483932, 0.81068432, 0.69905581, 0.57375342],
       [0.51979489, 0.63331324, 0.7344436

In [141]:
n = 5 
p = 3
np.random.choice(range(n*n), p, replace=True)

array([10, 15,  6])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [146]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

array([[0.19168349, 0.07226187, 0.41048525, 0.86978435, 0.23110525,
        0.21436993, 0.20352382, 0.60123055, 0.08814423, 0.03659416]])

#### 59. How to sort an array by the nth column? (★★☆)

In [153]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print()

print(Z[Z[:,1].argsort()])
Z[:,1].argsort()

[[9 9 0]
 [2 0 3]
 [9 2 2]]

[[2 0 3]
 [9 2 2]
 [9 9 0]]


array([1, 2, 0])

In [160]:
Z = np.random.randint(0,10,(3,3))
Z[Z[:,1].nindex[0]]

AttributeError: 'numpy.ndarray' object has no attribute 'nindex'

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)

In [164]:
Z = np.random.uniform(0,1,10)
z = 0.5

print(Z)

m = Z[np.abs(Z - z).argmin()]
print(m)

# np.abs(Z - z).argmin()

[0.5061745  0.36597467 0.36402942 0.69317928 0.3517718  0.24406377
 0.41533801 0.10393173 0.20845749 0.41555931]
0.5061744965152045


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [170]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)

print(A)
print(B)

it = np.nditer([A,B,None])

print(it)

for x,y,z in it: 
    z[...] = x + y
    
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [171]:
class NamedArray(np.ndarray):
    
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
        
        

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [180]:
A = np.random.randint(0,10,(2,5,3,4))

print(A.shape[:-2] + (-1,) )

# A.reshape(A.shape[:-2] + (-1,))

(2, 5, -1)


In [173]:
A = np.random.randint(0,10,(3,4,3,4))

# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)


# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[71 58 55 54]
 [62 44 56 60]
 [44 40 57 57]]
[[71 58 55 54]
 [62 44 56 60]
 [44 40 57 57]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [190]:
D = np.random.uniform(0,1,100)   
S = np.random.randint(0,10,100)  
# print(D)
print(S)
print()

D_sums = np.bincount(S, weights=D)
print(D_sums)

D_counts = np.bincount(S)
print(D_counts)

D_means = D_sums / D_counts
print(D_means)

[6 2 6 5 2 5 8 6 4 5 4 5 0 5 8 9 8 2 1 9 8 3 1 5 8 2 7 1 3 1 0 6 0 4 6 2 0
 1 4 4 0 5 4 4 2 6 2 3 3 1 5 4 2 8 3 3 0 3 8 3 3 1 9 0 4 6 6 7 5 1 6 9 7 7
 8 1 0 7 0 3 6 8 0 5 9 7 8 8 6 1 4 3 4 1 5 6 3 0 8 7]

[5.37648499 6.32160073 3.75988839 6.58652154 5.05264191 4.27492031
 6.81678185 3.91629179 4.85433748 2.39218488]
[11 11  8 12 11 11 12  7 12  5]
[0.48877136 0.57469098 0.46998605 0.5488768  0.45933108 0.38862912
 0.56806515 0.55947026 0.40452812 0.47843698]


#### 69. How to get the diagonal of a dot product? (★★★)

In [194]:
import pandas as pd

D = np.random.uniform(0,1,100)   
S = np.random.randint(0,10,100)

print(pd.Series(D).groupby(S).mean())


# same thing done by numpy 

D_sums = np.bincount(S, weights=D)
# print(D_sums)

D_counts = np.bincount(S)
# print(D_counts)

D_means = D_sums / D_counts
print(D_means)


# other ways 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

0    0.667537
1    0.559808
2    0.326714
3    0.444016
4    0.452157
5    0.444523
6    0.563676
7    0.559524
8    0.531412
9    0.492529
dtype: float64
[0.66753678 0.55980771 0.32671351 0.44401617 0.45215748 0.44452283
 0.56367587 0.55952412 0.53141198 0.4925293 ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [198]:
Z = np.array([1,2,3,4,5])
nz = 3
np.zeros(len(Z) +(len(Z)-1)*(nz))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [204]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[0::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [207]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [223]:
A = np.random.random((5,3))
print(A)

i = 1
j = 3

B = A.copy()
B[j,:],B[i,:] = A[i,:],A[j,:]
print(B)


A[[i,j]] = A[[j,i]]
print(A==B)

[[0.22939556 0.78294464 0.8178895 ]
 [0.40854841 0.3965647  0.16724322]
 [0.49479398 0.93915373 0.75824961]
 [0.36079744 0.3303456  0.90234893]
 [0.72114164 0.98107978 0.18358185]]
[[0.22939556 0.78294464 0.8178895 ]
 [0.36079744 0.3303456  0.90234893]
 [0.49479398 0.93915373 0.75824961]
 [0.40854841 0.3965647  0.16724322]
 [0.72114164 0.98107978 0.18358185]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

array([[63, 63, 15],
       [77, 26, 20],
       [71, 40, 54],
       [14, 29, 21],
       [14, 86, 88],
       [98, 90,  5],
       [ 2, 58, 11],
       [88, 11, 10],
       [ 2, 19,  5],
       [59, 10, 30]])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [238]:
Z = np.arange(20);print(Z)
ret = np.cumsum(Z, dtype=np.float64)
ret[3:] = ret[3:] - ret[:-3]
print(ret[2:]/3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
def moving_average(Z, n=3) :
    ret = np.cumsum(Z, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] / n

Z = np.arange(20)

print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)