In [1]:
import numpy as np

### dtype

In [ ]:
arr = np.array([1,2,3,9], dtype = np.int32)
print(arr.astype(float))

# np.nan 
np.array([np.nan, 1, np.inf], dtype=np.float32)

### making arrays

In [3]:
# linspace
np.linspace(10,100,9, endpoint=False)
np.linspace(10,100,9)

#reshape
arr = np.arange(0,10)    # excludes last 
np.reshape(arr,(2,5))

#flatten
flattened = arr.flatten()

# transpose with dims = 2
arr = np.transpose(arr)

# transpose with ndims > 2 
arr = np.arange(24)
arr = np.reshape(arr, (3, 4, 2))
transposed = np.transpose(arr, axes = (1,2,0))   # (2.4.3) if axes is not specified

### math operations

In [7]:
np.exp(arr) 
np.log(arr)
np.log10(arr)

### generate random arrays

In [ ]:
np.random.randint(5)
np.random.randint(5, high=6)
random_arr = np.random.randint(3, high=100, size=(2, 2))

### distributions

In [ ]:
np.random.uniform(low=-1.5, high=2.2)
np.random.normal(loc=1.5, scale=3.5)     # loc = mean , scale = std deviation
np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))

### custom sampling

In [ ]:
colors = ['red', 'blue', 'green']
np.random.choice(colors)
np.random.choice(colors, size=2)
np.random.choice(colors, size=(2, 2), p=[0.8, 0.19, 0.01]

### array indexing

In [ ]:

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[0:1, 1:]                          # array([[2, 3]])

### filtering

In [8]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, -6],
                [np.nan, -2, 1]])

print(np.isnan(arr))

[[False False  True]
 [False  True False]
 [ True False False]]


### argmin & argmax

In [ ]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])



print(np.argmin(arr[0]))   # 2
print(np.argmin(arr))      # 5

print(np.argmin(arr[:,1]))  # 0 

print(repr(np.argmin(arr, axis=0)))    # array([2, 0, 1])
print(repr(np.argmin(arr, axis=1)))    # array([2, 2, 0])
print(repr(np.argmax(arr, axis=-1)))   # array([1, 1, 1])

### concatenate

In [11]:
arr1 = np.array([[0, 72, 3],
                 [1, 3, -60],
                 [-3, -2, 4]])

arr2 = np.array([[-15, 6, 1],
                 [8, 9, -4],
                 [5, -21, 18]])

print(repr(np.concatenate([arr1, arr2])))
print()
print(repr(np.concatenate([arr1, arr2], axis=1)))



array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])

array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])


### operations along an axis

In [12]:
# np.sum
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

print(np.sum(arr))   
print(repr(np.sum(arr, axis=0)))    # array([ -2,  73, -53])    
print(repr(np.sum(arr, axis=1)))    # array([ -2,  73, -53])

18
array([ -2,  73, -53])
array([ 75, -56,  -1])


### np.where

```
The interesting thing about np.where is that it must be applied with exactly 1 or 3 arguments. When we use 3 arguments, the first argument is still the boolean array. However, the next two arguments represent the True replacement values and the False replacement values,

Note that our second and third arguments necessarily had the same shape as the first argument. However, if we wanted to use a constant replacement value, e.g. -1, we could incorporate broadcasting. Rather than using an entire array of the same value, we can just use the value itself as an argument.

```

In [ ]:
arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 1]])

x_ind, y_ind = np.where(arr == 0)  

In [ ]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-2, -5], [-1, -8]])
print(repr(np.where(np_filter, positives, negatives)))

### np.any & np.all

In [ ]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])

print(repr(np.any(arr > 0, axis=0)))   # array([ True,  True,  True])
print(repr(np.any(arr > 0, axis=1)))   # array([False,  True,  True])
print(repr(np.all(arr > 0, axis=1)))   # array([False, False,  True])


### np.cumsum

In [ ]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print(repr(np.cumsum(arr)))
print(repr(np.cumsum(arr, axis=0)))
print(repr(np.cumsum(arr, axis=1)))

### statistics

In [14]:
arr.min()
arr.std()

31.262330900515614

## EXERCISES

Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [ ]:
z = np.zeros((5,5), dtype = np.int32)

for i in range(5):
    for j in range(5):
        if j - i == -1:
            z[i,j] = i 
            
print(z) 

Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
Z1 = np.zeros((8,8), dtype = np.uint8)

box = 0 
for i in range(8):
    for j in range(8):
        if (i+j)%2 !=0 :
            Z1[i,j] = 1

print(Z1)
print()

Z2 = np.zeros((8,8),dtype=int)

Z2[1::2,::2] = 1
Z2[::2,1::2] = 1

print(Z2)

Z1 == Z2

Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element

In [18]:
np.unravel_index(99,(6,7,8))

Create a checkerboard 8x8 matrix using the tile function

In [ ]:
z = np.array([[0,1],[1,0]])
Z = np.tile(z,(4,4))


Normalize a 5x5 random matrix 

In [ ]:
Z = np.random.random((5,5))Z
Z = (Z - Z.mean())/Z.std()

Z = (Z - np.mean (Z)) / (np.std (Z))

Given a 1D array, negate all elements which are between 3 and 8, in place

In [20]:
Z1 = np.random.random(10)

Z2 = np.array([-x if  x < 8.0 and x > 3 else x for x in list(Z)])

How to round away from zero a float array

In [ ]:
Z = np.random.uniform(low=-1, high=1, size=(10,))
Z = np.random.normal(loc=-1, scale=1, size=(10,))

print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

How to find common values between two arrays

In [ ]:
Z1 = np.random.randint(low=0, high=10, size=(10,))
Z2 = np.random.randint(low=0, high=10, size=(10,))

print(Z1[Z1==Z2])               # matches only at same index
print(np.intersect1d(Z1,Z2))    # finds intesection 

How to get the dates of yesterday, today and tomorrow

In [ ]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64("today")
tomorrow = np.datetime64("today") + np.timedelta64(1)

How to get all the dates corresponding to the month of July 2016

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

Create a 5x5 matrix with row values ranging from 0 to 4 

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)

convert to polar coordinates

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]

R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y,X)

print(R)
print(T)

Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
Z = np.random.random(10)
Z[Z.argmax()] = 0

equivalent of enumerate for numpy arrays

In [ ]:
for index, value in np.ndenumerate(Z):
    print(index, value)

Generate a generic 2D Gaussian-like array 

In [ ]:
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0

G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )

Subtract the mean of each row of a matrix

In [ ]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

How to sort an array by the nth column

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print()

print(Z[Z[:,1].argsort()])
Z[:,1].argsort()

How to tell if a given 2D array has null columns

In [ ]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

Find the nearest value from a given value in an array

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5

print(Z)

m = Z[np.abs(Z - z).argmin()]
print(m)

# np.abs(Z - z).argmin()

Considering a four dimensions array, how to get sum over the last two axis at once

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))

sum = A.sum(axis=(-2,-1))
print(sum)

How to swap two rows of an array

In [ ]:
A = np.random.random((5,3))

i = 1
j = 3

B = A.copy()
B[j,:],B[i,:] = A[i,:],A[j,:]
print(B)


A[[i,j]] = A[[j,i]]
print(A==B)